# Generated by Django 6.0.6 on 2026-06-19 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transcation',
            new_name='Transaction',
        ),
    ]
